---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: eck-operator-release
  namespace: flux-system
spec:
  interval: 1m
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./infrastructure/base/eck-operator/release"
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: eck-operator
      namespace: eck-operator
  timeout: 5m

