---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: eck-operator-crds
  namespace: flux-system
spec:
  dependsOn:
    - name: eck-operator-release
      namespace: eck-operator
  interval: 1m
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./infrastructure/base/eck-operator/crds"
  timeout: 5m
  postBuild:
    substitute:
      version: 8.12.0
