apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: log-storage
  namespace: elasticsearch
spec:
  count: 1
  elasticsearchRef:
    name: log-storage
    namespace: elasticsearch
  podTemplate:
    spec:
      containers:
          name: kibana
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsUser: 1000
  version: 8.14.1